name: Deploy to Google Cloud

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Install Python dependencies
        run: |
          cd backend
          pip install -r requirements.txt
      
      - name: Install Node dependencies
        run: |
          cd frontend
          npm ci
      
      - name: Run Python tests
        run: |
          cd backend
          pytest tests/ -v
      
      - name: Run TypeScript checks
        run: |
          cd frontend
          npm run type-check
      
      - name: Run linting
        run: |
          cd frontend
          npm run lint

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
      
      - name: Configure Docker
        run: gcloud auth configure-docker
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
      
      - name: Build and deploy backend
        run: |
          cd backend
          docker build -t gcr.io/$PROJECT_ID/travel-history-backend:$GITHUB_SHA .
          docker push gcr.io/$PROJECT_ID/travel-history-backend:$GITHUB_SHA
          
          gcloud run deploy travel-history-backend \
            --image gcr.io/$PROJECT_ID/travel-history-backend:$GITHUB_SHA \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --set-env-vars GOOGLE_CLOUD_PROJECT=$PROJECT_ID \
            --memory 2Gi \
            --cpu 2 \
            --max-instances 10
      
      - name: Build and deploy frontend
        run: |
          cd frontend
          npm ci
          npm run build
          npm run export
          
          firebase deploy --only hosting --token ${{ secrets.FIREBASE_TOKEN }}
      
      - name: Deploy Firestore rules
        run: firebase deploy --only firestore:rules --token ${{ secrets.FIREBASE_TOKEN }}
      
      - name: Deploy Storage rules
        run: firebase deploy --only storage --token ${{ secrets.FIREBASE_TOKEN }}
